language: node_js
node_js:
  - "0.10"

env:
  - CHROME_BIN=/opt/google/chrome/chrome

before_script:
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - $deployKey
